import {
  Zap,
  Waves,
  PiggyBank,
  Shield,
  Coins,
  LineChart,
  LucideIcon,
  Percent,
  TrendingUp,
  Sun,
  Moon,
  Menu,
  X,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Plus,
  Minus,
  Settings,
  LogOut,
  User,
  Wallet,
  History,
  Search,
  ExternalLink,
  Copy,
  Check,
  AlertCircle,
  Info,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  sun: Sun,
  moon: Moon,
  menu: Menu,
  close: X,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  plus: Plus,
  minus: Minus,
  settings: Settings,
  logout: LogOut,
  user: User,
  wallet: Wallet,
  history: History,
  search: Search,
  external: ExternalLink,
  copy: Copy,
  check: Check,
  warning: AlertCircle,
  info: Info,
  
  // Feature section icons
  zap: Zap,
  waves: Waves,
  piggyBank: PiggyBank,
  shield: Shield,
  coins: Coins,
  lineChart: LineChart,
  percentage: Percent,
  trendingUp: TrendingUp,
} as const;
